// Code generated by go-base. DO NOT EDIT.
package server

import (
	"google.golang.org/grpc"

	{{.importPackages}}
)

// RegisterServices 注册所有 gRPC 服务
// 在此函数中添加新的服务注册，类似 HTTP 的 handler.RegisterHandlers
func RegisterServices(grpcServer *grpc.Server, ctx *svc.ServiceContext) {
	{{.serviceRegistrations}}
}
