// Code generated by go-base. DO NOT EDIT.
package server

import (
	"google.golang.org/grpc"

	{{.importPackages}}
)

// RegisterServices registers all gRPC services.
// Add new service registrations here, similar to HTTP handler.RegisterHandlers.
func RegisterServices(grpcServer *grpc.Server, ctx *svc.ServiceContext) {
	{{.serviceRegistrations}}
}
